Attempt of 3 get/api/categories
ollieemb/beProjectOE pull request #1
Opened 2023-02-20 14:46 UTC by ollieemb

2023-02-20 15:15 UTC, johnhutcheon commented on __tests__/app.test.js
> +            expect(body.categories[2].description).toBe("Games involving physical skill");
Rather than checking an individual element in the array, could we please iterate over it to check everything in the array?

2023-02-20 15:16 UTC, johnhutcheon commented on controllers/categoriesControllers.js
> +    });
This is the correct place to put the catch block, but at the moment it isn't being picked up anywhere? Could we please add some error handling middleware?

2023-02-20 15:17 UTC, johnhutcheon requested changes
Hey Ollie, if you could just check my comments please and amend the test, plus add some error handling, that'd be great. Please resubmit once you've done this so we can check. 🙂

2023-02-20 15:57 UTC, yalicee commented on __tests__/app.test.js
> +            expect(body.categories[2].description).toBe("Games involving physical skill");
Don't need these two lines

2023-02-20 15:58 UTC, yalicee requested changes
Please add testing for 404 error :)

2023-02-21 10:28 UTC, emilyb93 commented on app.js
> +app.use(express.json());
You're not doing a post request so you don't need this yet. Remove it until it is necessary

2023-02-21 10:29 UTC, emilyb93 approved these changes
Remove the express.json() line in your app file and then this is fine to merge

2023-02-21 10:32 UTC, merged